version: '3'
services:
  app:
    container_name: node-ts-apollo-mongodb
    restart: always
    build: .
    ports:
      - '80:4000'
    volumes:
      - ./src:/home/app/src
      # - C:\Users\Stire\Desktop\projects\node-ts-apollo-mongodb\src:/home/app/src
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
